--liquibase formatted sql

--changeset Borja:G4GENWrapper_0_1 dbms:db2i failOnError:false runOnChange:false
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
CALL QSYS2.QCMDEXC('ADDRPYLE SEQNBR(1500) MSGID(CPA32B2) RPY(''I'')', 45);

--changeset Borja:G4GENWrapper_0_2 runAlways:true dbms:db2i
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)', 26);

--changeset Borja:G4GENWrapper_biblioteca dbms:db2i
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLSCHEMAS where TABLE_SCHEM = 'G4GENWRAPPER';

CREATE COLLECTION G4GENWRAPPER;

--changeset Borja:G4GENWrapper_1 
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'MENU';

CREATE TABLE G4GENWRAPPER.MENU (
	ID VARCHAR(32) PRIMARY KEY,
	NOMBRE VARCHAR(50),
	PRINCIPAL NUMERIC(1,0) UNIQUE
);

--changeset Borja:G4GENWrapper_2 
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'PAGINA';

CREATE TABLE G4GENWRAPPER.PAGINA (
	ID VARCHAR(32) PRIMARY KEY,
	URL VARCHAR(200),
	NOMBRE VARCHAR(50),
	DESCRIPCION VARCHAR(250)
);

--changeset Borja:G4GENWrapper_3 
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'RELMENPAG';

CREATE TABLE G4GENWRAPPER.RELMENPAG (
	MENU VARCHAR(32),
	PAGINA VARCHAR(32),
	ORDEN NUMERIC(3),
	PRIMARY KEY(MENU, PAGINA),
	FOREIGN KEY(MENU) REFERENCES G4GENWRAPPER.MENU(ID),
	FOREIGN KEY(PAGINA) REFERENCES G4GENWRAPPER.PAGINA(ID)
);

--changeset Borja:G4GENWrapper_4
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'RELPAGSUBPAG';

CREATE TABLE G4GENWRAPPER.RELPAGSUBPAG (
	PAGINA VARCHAR(32),
	SUBPAGINA VARCHAR(32),
	ORDEN NUMERIC(3),
	PRIMARY KEY(PAGINA, SUBPAGINA),
	FOREIGN KEY(PAGINA) REFERENCES G4GENWRAPPER.PAGINA(ID),
	FOREIGN KEY(SUBPAGINA) REFERENCES G4GENWRAPPER.PAGINA(ID)
);

--changeset Borja:G4GENWrapper_5
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'USUARIO';

CREATE TABLE G4GENWRAPPER.USUARIO (
	NIF VARCHAR(9) PRIMARY KEY,
	NOMBRE VARCHAR(50),
	PRIMERAPELLIDO VARCHAR(50),
	SEGUNDOAPELLIDO VARCHAR(50),
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(50),
	ACTUALIZARPASSWORD NUMERIC(1,0),
	SUPERUSUARIO NUMERIC(1,0),
	USUARIOAS400 VARCHAR(10),
	PASSWORDAS400 VARCHAR(10)
);

--changeset Borja:G4GENWrapper_6
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'ROL';

CREATE table G4GENWRAPPER.ROL (
	ID Varchar(32) PRIMARY KEY,
	NOMBRE VARCHAR(50),
	DESCRIPCION VARCHAR(250)
);

--changeset Borja:G4GENWrapper_7
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'RELUSUARIOROL';

CREATE table G4GENWRAPPER.RELUSUARIOROL (
	USUARIO VARCHAR(9),
	ROL VARCHAR(32),
	PRIMARY KEY(USUARIO, ROL),
	FOREIGN KEY(USUARIO) REFERENCES G4GENWRAPPER.USUARIO(NIF),
	FOREIGN KEY(ROL) REFERENCES G4GENWRAPPER.ROL(ID)
);

--changeset Borja:G4GENWrapper_8
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES WHERE TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'RELROLPAGINA';

CREATE TABLE G4GENWRAPPER.RELROLPAGINA (
	ROL VARCHAR(32),
	PAGINA VARCHAR(32),
	PRIMARY KEY (ROL,PAGINA),
	FOREIGN KEY(ROL) REFERENCES G4GENWRAPPER.ROL(ID),
	FOREIGN KEY(PAGINA) REFERENCES G4GENWRAPPER.PAGINA(ID)
);


--changeset Borja:G4GENWrapper_9
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'ANUNCIO';

CREATE TABLE G4GENWRAPPER.ANUNCIO (
	ID VARCHAR(32) PRIMARY KEY,
	ASUNTO VARCHAR(200),
	TEXTOANUNCIO VARCHAR(3000),
	FECHADEPUBLICACION TIMESTAMP,
	DESCRIPCIONBREVE VARCHAR(500)
);

--changeset Borja:G4GENWrapper_10
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'PAIS';

CREATE TABLE G4GENWRAPPER.PAIS (
	CODIGO NUMERIC(3,0) PRIMARY KEY,
	DESCRIPCION VARCHAR(120)
);

--changeset Borja:G4GENWrapper_11
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'TERCERO';

CREATE TABLE G4GENWRAPPER.TERCERO (
	NIF VARCHAR(9) PRIMARY KEY,
	NATURALEZA NUMERIC(1,0),
	PAIS NUMERIC(3,0),
	RAZONSOCIAL VARCHAR(120),
	NOMBRE VARCHAR(20),
	APELLIDO1 VARCHAR(25),
	APELLIDO2 VARCHAR(25),
	TELEFONO VARCHAR(25),
	EMAIL VARCHAR(60),
	FECHAALTA DATE,
	FACHAMODIFICACION DATE,
	FECHABAJA DATE,
	VIA VARCHAR(5),
	DENOMINACION VARCHAR(25),
	NUMERO NUMERIC(4,0),
	BIS VARCHAR(1),
	NUMERO2 NUMERIC(4,0),
	BIS2 VARCHAR(1),
	KILOMETRO NUMERIC(4,3),
	BLOQUE VARCHAR(2),
	PORTAL VARCHAR(2),
	ESCALERA VARCHAR(2),
	PLANTA VARCHAR(3),
	PUERTA VARCHAR(4),
	PROVINCIA NUMERIC(2,0),
	MUNICIPIO NUMERIC(3,0),
	CODIGOPOSTAL NUMERIC(5,0),
	CATASTRALMANZANA VARCHAR(7),
	CATASTRALCENTRO VARCHAR(7),
	CATASTRALCARGO NUMERIC(4,0),
	CATASTRALCONTROL1 VARCHAR(1),
	CATASTRALCONTROL2 VARCHAR(1),
	ACTUALIZADO NUMERIC(1,0) DEFAULT 0,
	FOREIGN KEY(PAIS) REFERENCES G4GENWRAPPER.PAIS(CODIGO),
	FOREIGN KEY(PROVINCIA) REFERENCES G4GENWRAPPER.PROVINCIA(CODIGO),
	FOREIGN KEY(PROVINCIA,MUNICIPIO) REFERENCES G4GENWRAPPER.MUNICIPIO(PROVINCIA,CODIGO)
);

--changeset Borja:G4GENWrapper_12
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'PARAMETRO';

CREATE TABLE G4GENWRAPPER.PARAMETRO (
	ID VARCHAR(32) PRIMARY KEY,
	CLAVE VARCHAR(50) UNIQUE,
	DESCRIPCION VARCHAR(200),
	VALOR VARCHAR(500)
);

CREATE INDEX G4GENWRAPPER.PARAMETRO_INDICES_1 ON G4GENWRAPPER.PARAMETRO(CLAVE);

--changeset Borja:G4GENWrapper_13
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'PROVINCIA';

CREATE TABLE G4GENWRAPPER.PROVINCIA (
	CODIGO NUMERIC(2,0) PRIMARY KEY,
	DESCRIPCION VARCHAR(25)
);

--changeset Borja:G4GENWrapper_14
--preconditions onFail:MARK_RAN onError:MARK_RAN dbms:db2i
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM SYSIBM.SQLTABLES where TABLE_SCHEM = 'G4GENWRAPPER' AND TABLE_TYPE = 'TABLE' AND TABLE_NAME = 'MUNICIPIO';

CREATE TABLE G4GENWRAPPER.MUNICIPIO (
	PROVINCIA NUMERIC(2,0),
	CODIGO NUMERIC(3,0),
	DESCRIPCION VARCHAR(50),
	CP NUMERIC(5,0),
	ACTUALIZADO NUMERIC(1,0) DEFAULT 0,
	PRIMARY KEY (PROVINCIA, CODIGO),
	FOREIGN KEY(PROVINCIA) REFERENCES G4GENWRAPPER.PROVINCIA(CODIGO)
);
